version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/multinode-nodejs:test
    restart: unless-stopped
    ports:
    - '3080:3000'
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  custom:
    image: redis
    restart: unless-stopped
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
